# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: German Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: staging
remotedatabaseurl: "https://G205SDGs.github.io/sdg-data"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_json:
  - data: meta
    json: 'https://G205SDGs.github.io/sdg-data/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://G205SDGs.github.io/sdg-data/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://G205SDGs.github.io/sdg-data/meta/schema.json'
  - data: reporting
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://G205SDGs.github.io/sdg-data/stats/reporting.json'
  - data: translations
    # Pin to version 0.3.0 of the translation repository.
    json: 'https://JustusCas.github.io/sdg-translations/translations.json'

analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: sdg-indicators@destatis.de
  suggestions: sdg-indicators@destatis.de
  functional: sdg-indicators@destatis.de
###################################################################################################

# Github Repo for Data
repo_name: sdg-data
branch: develop
org_name: G205SDGs

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian.
country:
  name: Germany
  adjective: German

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
    - de
    - en

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: general.goals
  - path: /reporting-status/
    translation_key: menu.reporting_status
  - path: /about/
    translation_key: menu.about
  - path: /guidance/
    translation_key: menu.guidance

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "de"
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Use a remote Jekyll theme.
remote_theme: open-sdg/open-sdg@0.9.4
goal_image_base: https://g205sdgs.github.io/sdg-indicators/assets/img/goals

custom_css:
  - /assets/css/custom.css

custom_js:
  - /assets/js/custom.js



# Mapping
map_options:

  #tileURL: https://api.mapbox.com/styles/v1/mobosse/cjzo8dsnt0bz71cohx8l8etpg/tiles/256/{z}/{x}/{y}?&access_token={accessToken}
  #tileURL: https://api.mapbox.com/styles/v1/mobosse/cjzmrn62k0ek11cmgea7a1i1h/tiles/256/{z}/{x}/{y}?&access_token={accessToken}
  tileURL: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  tileOptions:
    id: mapbox.light
    #accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjanplNTNhMmQwMTFjM21wNHEzazRlejhwIn0.ecHE5G83cklfW5AXYjI_0A
    accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjazU1M2trazQwYnFwM2trYmdwNm9rOWxkIn0.u36w-RJPqoTGmivl_zED1w
    attribution: <a href="https://www.openstreetmap.org/copyright">&copy; OpenStreetMap</a> contributors |<br class="visible-xs"> <a href="https://www.bkg.bund.de">&copy; GeoBasis-De / BKG 2020</a> |<br class="hidden-lg"> <a href="https://www.destatis.de/DE/Home/_inhalt.html">&copy; Statistisches Bundesamt (Destatis), 2020</a>

  #---#1 GoalDependendMapColor---start----------------------------------------------------------------------------------------------------------------------------------------
  #colorRange: ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"]
  colorRange: [["#FCE9EB", "#F7BDC4", "#F2929D", "#ED6676", "#E83A4F", "#E5243B", "#B71D2F", "#891623", "#5C0E18", "#2E070C"],
               ["#FCF8EB", "#F7E9C2", "#F2DB9A", "#EDCD72", "#E8BE49", "#E5B735", "#CEA530", "#A08025", "#735C1B", "#453710"],
               ["#EDF5EB", "#C9E2C3", "#A6CF9C", "#82BC74", "#5EA94C", "#4C9F38", "#3D7F2D", "#2E5F22", "#1E4016", "#0F200B"],
               ["#F9E8EA", "#EEBAC0", "#E28C96", "#D65E6C", "#CB3042", "#C5192D", "#9E1424", "#760F1B", "#4F0A12", "#270509"],
               ["#FFEBE9", "#FFC4BC", "#FF9D90", "#FF7564", "#FF4E37", "#FF3A21", "#CC2E1A", "#992314", "#66170D", "#330C07"],
               ["#E9F8FB", "#BEEBF6", "#93DEF0", "#67D1EA", "#3CC4E5", "#26BDE2", "#1E97B5", "#177188", "#0F4C5A", "#08262D"],
               ["#FFF9E7", "#FEEDB6", "#FEE185", "#FDD554", "#FCC923", "#FCC30B", "#CA9C09", "#977507", "#654E04", "#322702"],
               ["#F6E8EC", "#E3BAC6", "#D18CA1", "#BE5E7B", "#AB3055", "#A21942", "#821435", "#610F28", "#410A1A", "#20050D"],
               ["#FFF0E9", "#FED2BE", "#FEB492", "#FE9666", "#FD783B", "#FD6925", "#CA541E", "#983F16", "#652A0F", "#331507"],
               ["#FCE7F0", "#F5B8D1", "#EE89B3", "#E75A95", "#E02B76", "#DD1367", "#B10F52", "#850B3E", "#580829", "#2C0415"],
               ["#FFF5E6", "#FEE2B3", "#FECE80", "#FEBA4D", "#FDA71A", "#FD9D00", "#CA7E00", "#985E00", "#653F00", "#331F00"],
               ["#FAF5EA", "#EFE0C0", "#E4CC96", "#D9B86C", "#CEA342", "#C9992D", "#A17A24", "#795C1B", "#503D12", "#281F09"],
               ["#ECF2EC", "#C5D8C7", "#9FBFA2", "#79A57C", "#528B57", "#3F7E44", "#326536", "#264C29", "#19321B", "#0D190E"],
               ["#E7F5FB", "#B6E0F4", "#85CBEC", "#54B6E4", "#23A1DD", "#0A97D9", "#0879AE", "#065B82", "#043C57", "#021E2B"],
               ["#EEF9EA", "#CCECBF", "#ABE095", "#89D36B", "#67C640", "#56C02B", "#459A22", "#34731A", "#224D11", "#112609"],
               ["#E6F0F5", "#B3D2E2", "#80B4CE", "#4D95BA", "#1A77A7", "#00689D", "#00537E", "#003E5E", "#002A3F", "#00151F"],
               ["#E8EDF0", "#BAC8D2", "#8CA4B5", "#5E7F97", "#305A79", "#19486A", "#143A55", "#0F2B40", "#0A1D2A", "#050E15"]]
  #---#1 GoalDependendMapColor---stop-------------------------------------------------------------------------------------------------------------------------------------------

  # Set the color for boundaries that have no data.
  noValueColor:  '#f0f0f0'
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  #styleNormal:
    #weight: 1
    #opacity: 1
    #color: #888
    #fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  #styleHighlighted:
    #weight: 1
    #opacity: 1
    #color: #111
    #fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  #styleStatic:
    #weight: 2
    #opacity: 1
    #fillOpacity: 0
    #color: #172d44
    #dashArray: 5,5
map_layers:
  #Country
  #- min_zoom: 5
    #max_zoom: 10
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/c362832ce5d14728a6fb2b079525be0b_4.geojson
    #nameProperty: ctry17nm
    #idProperty: ctry17cd
    #staticBorders: true
    # link: https://hub.arcgis.com/datasets/c362832ce5d14728a6fb2b079525be0b_4/data
  #Region
  - min_zoom: 0
    max_zoom: 20
    #serviceUrl: https://opendata.arcgis.com/datasets/33a15b8fd5624dd4800cc33ab5bad761_0.geojson
    serviceUrl: https://g205sdgs.github.io/sdg-indicators/assets/maps/Ländergrenzen_ohne_Seegrenzen.geojson
    nameProperty: GEN
    idProperty: AGS #OBJECTID
    staticBorders: true
    # link: https://hub.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4
  #Local Authority
  #- min_zoom: 6
    #max_zoom: 10
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4.geojson
    #nameProperty: lad16nm
    #idProperty: lad16cd
    #staticBorders: false
    # link: https://hub.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4
  #County
  #- min_zoom: 8
    #max_zoom: 9
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3.geojson
    #nameProperty: cty18nm
    #idProperty: cty18cd
# link: https://hub.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3
