# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: German Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: staging
remotedatabaseurl: "https://G205SDGs.github.io/sdg-data"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_json:
  - data: meta
    json: 'https://G205SDGs.github.io/sdg-data/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://G205SDGs.github.io/sdg-data/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://G205SDGs.github.io/sdg-data/meta/schema.json'
  - data: reporting
    # Replace my-github-org and open-sdg-data-starter as needed.
    json: 'https://G205SDGs.github.io/sdg-data/stats/reporting.json'
  - data: translations
    # Pin to version 0.3.0 of the translation repository.
    json: 'https://JustusCas.github.io/sdg-translations/translations.json'

analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: sdg-indicators@destatis.de
  suggestions: sdg-indicators@destatis.de
  functional: sdg-indicators@destatis.de
###################################################################################################

# Github Repo for Data
repo_name: sdg-data
branch: develop
org_name: G205SDGs

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian.
country:
  name: Germany
  adjective: German

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
    - de
    - en

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: general.goals
  - path: /reporting-status/
    translation_key: menu.reporting_status
  - path: /about/
    translation_key: menu.about
  - path: /guidance/
    translation_key: menu.guidance

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "de"
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Use a remote Jekyll theme.
remote_theme: open-sdg/open-sdg@0.8.1
goal_image_base: https://g205sdgs.github.io/sdg-indicators/assets/img/goals

custom_css:
  - /assets/css/custom.css



# Mapping
map_options:
  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?&access_token={accessToken}
  #style: mapbox://styles/mobosse/cjzmrn62k0ek11cmgea7a1i1h
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoibW9ib3NzZSIsImEiOiJjanplNTNhMmQwMTFjM21wNHEzazRlejhwIn0.ecHE5G83cklfW5AXYjI_0A #pk.eyJ1IjoiYnJvY2tmYW5uaW5nMSIsImEiOiJjaXplbmgzczgyMmRtMnZxbzlmbGJmdW9pIn0.LU-BYMX69uu3eGgk0Imibg
    attribution: <a href="https://www.mapbox.com">Mapbox</a> # | <a href="http://geoportal.statistics.gov.uk/">ONS</a>

  # Control the choropleth color range. See https://gka.github.io/chroma.js/#chroma-brewer
  #Goal 5:
  #colorRange: ['#FFD9D5','#FFC8C1','#FFB6AD','#FFA499','#FF9385','#FF8171','#FF6F5D','#FF5D49','#FF4C35','#FF3A21']
  #Goal 8:
  colorRange: ["#F6E8EC", "#EED3DB", "#E5BFCA", "#DDAAB9", "#D495A8", "#CC8197", "#C46C86", "#BB5775", "#B34264", "#AA2E53","#A21942"]
  
  # Set the color for boundaries that have no data.
  noValueColor:  '#f0f0f0'
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  #styleNormal:
    #weight: 1
    #opacity: 1
    #color: #888
    #fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  #styleHighlighted:
    #weight: 1
    #opacity: 1
    #color: #111
    #fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  #styleStatic:
    #weight: 2
    #opacity: 1
    #fillOpacity: 0
    #color: #172d44
    #dashArray: 5,5
map_layers:
  #Country
  #- min_zoom: 5
    #max_zoom: 10
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/c362832ce5d14728a6fb2b079525be0b_4.geojson
    #nameProperty: ctry17nm
    #idProperty: ctry17cd
    #staticBorders: true
    # link: https://hub.arcgis.com/datasets/c362832ce5d14728a6fb2b079525be0b_4/data
  #Region
  - min_zoom: 0
    max_zoom: 20
    serviceUrl: https://opendata.arcgis.com/datasets/33a15b8fd5624dd4800cc33ab5bad761_0.geojson
    nameProperty: GEN
    idProperty: OBJECTID
    staticBorders: true
    # link: https://hub.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4
  #Local Authority
  #- min_zoom: 6
    #max_zoom: 10
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4.geojson
    #nameProperty: lad16nm
    #idProperty: lad16cd
    #staticBorders: false
    # link: https://hub.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4
  #County
  #- min_zoom: 8
    #max_zoom: 9
    #serviceUrl: https://geoportal1-ons.opendata.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3.geojson
    #nameProperty: cty18nm
    #idProperty: cty18cd
# link: https://hub.arcgis.com/datasets/b7507e654334481e8e0787f42c9028c1_3
